#! /usr/bin/ruby
require 'json'
require 'uri'
require 'net/http'
require 'timeout'
require 'benchmark'
require 'pp'

uri = URI('http://hotspot.yourkarma.com/api/status.json')

VERBOSE      = true
VERY_VERBOSE = false
TIMEOUT      = 10

def failure(message, exception, context = nil)
  if VERBOSE
    puts exception.class if VERY_VERBOSE
    puts exception
    puts context if context && VERY_VERBOSE
  end
  puts message
  exit 1
end

HTTP_ERRORS = [Timeout::Error, Errno::EINVAL, Errno::ECONNRESET, EOFError,
  Net::HTTPBadResponse, Net::HTTPHeaderSyntaxError, Net::ProtocolError,
  SocketError]

begin
  response = nil
  Timeout::timeout(TIMEOUT) do
    response = Net::HTTP.get_response(uri)
  end
  parsed = JSON::load(response.body)
rescue Timeout::Error => e
  failure "Request to Karma hotspot timed out.", e
rescue *HTTP_ERRORS => e
  failure "Not connected to a Karma hotspot.", e
rescue JSON::ParserError
  failure "Unexpected response from #{uri}.", e, parsed
end

begin
  message = "Network not connected."

  device = parsed.fetch "device"
  wifi   = device.fetch "wifiinterface"
  ssid   = wifi.fetch "ssid"

  message = "Unable to determine battery status."

  charging  = device.fetch "charging"
  battery   = device.fetch "batterypower"
  print "Battery #{battery}%. "
  puts charging ? "Charging." : "Not charging."

  message = "Connected to '#{ssid}', but WAN IP address is not assigned."

  wan        = device.fetch "waninterface"
  ip_address = wan.fetch "ipaddress"
rescue KeyError => e
  failure message, e, parsed
end

begin
  benchmark = nil
  Timeout::timeout(TIMEOUT) do
    benchmark = Benchmark.realtime do
      Net::HTTP.get_response(URI('https://www.google.com'))
    end
  end
  benchmark = (benchmark * 10).ceil / 10.0
rescue TimeoutError => e
  failure "Connected to '#{ssid}' and online, but the tubes are slow!", e, parsed
rescue *HTTP_ERRORS => e
  failure "Connected to '#{ssid}' and WAN IP address has be assigned, but request to Google failed.", e, parsed
end

puts "Connected to '#{ssid}' and online!"
puts "Request to Google took less than #{benchmark} seconds." if VERBOSE
